In [ ]:
# V1: Random forests no pre-processing
# V2: Random forests with combined wilderness area and soil type columns - loss of 0.2% compared to V1 (negliglbe)

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 100)

In [2]:
train_dataset = pd.read_csv('train.csv')
train_dataset.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,1,2596,51,3,258,0,510,221,232,148,6279,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5
1,2,2590,56,2,212,-6,390,220,235,151,6225,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5
2,3,2804,139,9,268,65,3180,234,238,135,6121,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
3,4,2785,155,18,242,118,3090,238,238,122,6211,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2
4,5,2595,45,2,153,-1,391,220,234,150,6172,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5

In [3]:
train_dataset.set_index('Id', inplace=True)
train_dataset.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2596,51,3,258,0,510,221,232,148,6279,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5
2,2590,56,2,212,-6,390,220,235,151,6225,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5
3,2804,139,9,268,65,3180,234,238,135,6121,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
4,2785,155,18,242,118,3090,238,238,122,6211,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2
5,2595,45,2,153,-1,391,220,234,150,6172,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,5

In [4]:
train_dataset.dtypes  # no object types! wow

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type7                            int64
Soil_Type8                            int64
Soil_Type9                            int64
Soil_Type10                           int64
Soil_Type11                           int64
Soil_Type12                           int64
Soil_Type13                           int64
Soil_Type14                           int64
Soil_Type15                           int64
Soil_Type16                           int64
Soil_Type17                           int64
Soil_Type18                           int64
Soil_Type19                           int64
Soil_Type20                           int64
Soil_Type21                           int64
Soil_Type22                           int64
Soil_Type23                           int64
Soil_Type24                           int64
Soil_Type25                           int64
Soil_Type26                           int64
Soil_Type27                           int64
Soil_Type28                           int64
Soil_Type29                           int64
Soil_Type30                           int64
Soil_Type31                           int64
Soil_Type32                           int64
Soil_Type33                           int64
Soil_Type34                           int64
Soil_Type35                           int64
Soil_Type36                           int64
Soil_Type37                           int64
Soil_Type38                           int64
Soil_Type39                           int64
Soil_Type40                           int64
Cover_Type                            int64
dtype: object

In [5]:
desc = train_dataset.describe().T
desc['missing'] = train_dataset.isna().sum()
desc
# no missing data! wow 
# notice that some soil types have a min and max of 0 :(

,count,mean,std,min,25%,50%,75%,max,missing
Elevation,15120.0,2749.322553,417.678187,1863.0,2376.0,2752.0,3104.00,3849.0,0
Aspect,15120.0,156.676653,110.085801,0.0,65.0,126.0,261.00,360.0,0
Slope,15120.0,16.501587,8.453927,0.0,10.0,15.0,22.00,52.0,0
Horizontal_Distance_To_Hydrology,15120.0,227.195701,210.075296,0.0,67.0,180.0,330.00,1343.0,0
Vertical_Distance_To_Hydrology,15120.0,51.076521,61.239406,-146.0,5.0,32.0,79.00,554.0,0
Horizontal_Distance_To_Roadways,15120.0,1714.023214,1325.066358,0.0,764.0,1316.0,2270.00,6890.0,0
Hillshade_9am,15120.0,212.704299,30.561287,0.0,196.0,220.0,235.00,254.0,0
Hillshade_Noon,15120.0,218.965608,22.801966,99.0,207.0,223.0,235.00,254.0,0
Hillshade_3pm,15120.0,135.091997,45.895189,0.0,106.0,138.0,167.00,248.0,0
Horizontal_Distance_To_Fire_Points,15120.0,1511.147288,1099.936493,0.0,730.0,1256.0,1988.25,6993.0,0
Wilderness_Area1,15120.0,0.237897,0.425810,0.0,0.0,0.0,0.00,1.0,0
Wilderness_Area2,15120.0,0.033003,0.178649,0.0,0.0,0.0,0.00,1.0,0
Wilderness_Area3,15120.0,0.419907,0.493560,0.0,0.0,0.0,1.00,1.0,0
Wilderness_Area4,15120.0,0.309193,0.462176,0.0,0.0,0.0,1.00,1.0,0
Soil_Type1,15120.0,0.023479,0.151424,0.0,0.0,0.0,0.00,1.0,0
Soil_Type2,15120.0,0.041204,0.198768,0.0,0.0,0.0,0.00,1.0,0
Soil_Type3,15120.0,0.063624,0.244091,0.0,0.0,0.0,0.00,1.0,0
Soil_Type4,15120.0,0.055754,0.229454,0.0,0.0,0.0,0.00,1.0,0
Soil_Type5,15120.0,0.010913,0.103896,0.0,0.0,0.0,0.00,1.0,0
Soil_Type6,15120.0,0.042989,0.202840,0.0,0.0,0.0,0.00,1.0,0
Soil_Type7,15120.0,0.000000,0.000000,0.0,0.0,0.0,0.00,0.0,0
Soil_Type8,15120.0,0.000066,0.008133,0.0,0.0,0.0,0.00,1.0,0
Soil_Type9,15120.0,0.000661,0.025710,0.0,0.0,0.0,0.00,1.0,0
Soil_Type10,15120.0,0.141667,0.348719,0.0,0.0,0.0,0.00,1.0,0
Soil_Type11,15120.0,0.026852,0.161656,0.0,0.0,0.0,0.00,1.0,0
Soil_Type12,15120.0,0.015013,0.121609,0.0,0.0,0.0,0.00,1.0,0
Soil_Type13,15120.0,0.031481,0.174621,0.0,0.0,0.0,0.00,1.0,0
Soil_Type14,15120.0,0.011177,0.105133,0.0,0.0,0.0,0.00,1.0,0
Soil_Type15,15120.0,0.000000,0.000000,0.0,0.0,0.0,0.00,0.0,0
Soil_Type16,15120.0,0.007540,0.086506,0.0,0.0,0.0,0.00,1.0,0
Soil_Type17,15120.0,0.040476,0.197080,0.0,0.0,0.0,0.00,1.0,0
Soil_Type18,15120.0,0.003968,0.062871,0.0,0.0,0.0,0.00,1.0,0
Soil_Type19,15120.0,0.003042,0.055075,0.0,0.0,0.0,0.00,1.0,0
Soil_Type20,15120.0,0.009193,0.095442,0.0,0.0,0.0,0.00,1.0,0
Soil_Type21,15120.0,0.001058,0.032514,0.0,0.0,0.0,0.00,1.0,0
Soil_Type22,15120.0,0.022817,0.149326,0.0,0.0,0.0,0.00,1.0,0
Soil_Type23,15120.0,0.050066,0.218089,0.0,0.0,0.0,0.00,1.0,0
Soil_Type24,15120.0,0.016997,0.129265,0.0,0.0,0.0,0.00,1.0,0
Soil_Type25,15120.0,0.000066,0.008133,0.0,0.0,0.0,0.00,1.0,0
Soil_Type26,15120.0,0.003571,0.059657,0.0,0.0,0.0,0.00,1.0,0
Soil_Type27,15120.0,0.000992,0.031482,0.0,0.0,0.0,0.00,1.0,0
Soil_Type28,15120.0,0.000595,0.024391,0.0,0.0,0.0,0.00,1.0,0
Soil_Type29,15120.0,0.085384,0.279461,0.0,0.0,0.0,0.00,1.0,0
Soil_Type30,15120.0,0.047950,0.213667,0.0,0.0,0.0,0.00,1.0,0
Soil_Type31,15120.0,0.021958,0.146550,0.0,0.0,0.0,0.00,1.0,0
Soil_Type32,15120.0,0.045635,0.208699,0.0,0.0,0.0,0.00,1.0,0
Soil_Type33,15120.0,0.040741,0.197696,0.0,0.0,0.0,0.00,1.0,0
Soil_Type34,15120.0,0.001455,0.038118,0.0,0.0,0.0,0.00,1.0,0
Soil_Type35,15120.0,0.006746,0.081859,0.0,0.0,0.0,0.00,1.0,0
Soil_Type36,15120.0,0.000661,0.025710,0.0,0.0,0.0,0.00,1.0,0
Soil_Type37,15120.0,0.002249,0.047368,0.0,0.0,0.0,0.00,1.0,0
Soil_Type38,15120.0,0.048148,0.214086,0.0,0.0,0.0,0.00,1.0,0
Soil_Type39,15120.0,0.043452,0.203880,0.0,0.0,0.0,0.00,1.0,0
Soil_Type40,15120.0,0.030357,0.171574,0.0,0.0,0.0,0.00,1.0,0
Cover_Type,15120.0,4.000000,2.000066,1.0,2.0,4.0,6.00,7.0,0

In [6]:
wilderness_cols = [c for c in train_dataset.columns if c.startswith('Wilderness')]
soil_type_cols = [c for c in train_dataset.columns if c.startswith('Soil_Type')]

In [7]:
# confirm any row only has 1 of wilderness or soil types set
train_dataset[wilderness_cols].sum(axis=1).max(), train_dataset[soil_type_cols].sum(axis=1).max()

(1, 1)

In [8]:
np.arange(1,len(wilderness_cols)+1)

array([1, 2, 3, 4])

In [9]:
# Combine into one column
train_dataset['Wilderness_Area'] = ((train_dataset[wilderness_cols]*np.arange(1,len(wilderness_cols)+1)).sum(axis=1))
train_dataset['Soil_Type'] = ((train_dataset[soil_type_cols]*np.arange(1,len(soil_type_cols)+1)).sum(axis=1))

In [10]:
train_dataset.drop(columns = wilderness_cols+soil_type_cols, inplace=True)

In [11]:
X = train_dataset.drop(columns=['Cover_Type'])
y = train_dataset['Cover_Type']

In [12]:
train_dataset['Cover_Type'].value_counts() # nice and balanced, wow

1    2160
2    2160
3    2160
4    2160
5    2160
6    2160
7    2160
Name: Cover_Type, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X_train.shape, X_test.shape

((12096, 12), (3024, 12))

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
clf = RandomForestClassifier(random_state=42, n_jobs=-1)

In [18]:
clf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [19]:
y_pred = clf.predict(X_test)
y_score = clf.predict_proba(X_test)

In [20]:
from sklearn.metrics import multilabel_confusion_matrix, roc_auc_score

In [21]:
multilabel_confusion_matrix(y_test, y_pred)

array([[[2515,   88],
        [  90,  331]],

       [[2520,   66],
        [ 129,  309]],

       [[2533,   63],
        [  73,  355]],

       [[2546,   29],
        [   7,  442]],

       [[2559,   49],
        [  17,  399]],

       [[2526,   66],
        [  57,  375]],

       [[2559,   25],
        [  13,  427]]])

In [22]:
roc_auc_score(y_test, y_score, multi_class='ovr') 
# V1: 0.986141412209138

0.9854174460616276

In [28]:
test_dataset = pd.read_csv('test.csv')
test_dataset.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,15121,2680,354,14,0,0,2684,196,214,156,6645,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,15122,2683,0,13,0,0,2654,201,216,152,6675,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,15123,2713,16,15,0,0,2980,206,208,137,6344,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,15124,2709,24,17,0,0,2950,208,201,125,6374,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,15125,2706,29,19,0,0,2920,210,195,115,6404,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [29]:
test_dataset.set_index('Id', inplace=True)
test_dataset.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
15121,2680,354,14,0,0,2684,196,214,156,6645,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15122,2683,0,13,0,0,2654,201,216,152,6675,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15123,2713,16,15,0,0,2980,206,208,137,6344,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15124,2709,24,17,0,0,2950,208,201,125,6374,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15125,2706,29,19,0,0,2920,210,195,115,6404,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [30]:
test_dataset['Wilderness_Area'] = ((test_dataset[wilderness_cols]*np.arange(1,len(wilderness_cols)+1)).sum(axis=1))
test_dataset['Soil_Type'] = ((test_dataset[soil_type_cols]*np.arange(1,len(soil_type_cols)+1)).sum(axis=1))
test_dataset.drop(columns = wilderness_cols+soil_type_cols, inplace=True)

In [31]:
X_score = test_dataset

In [32]:
y_score = pd.DataFrame(clf.predict(X_score), index=X_score.index, columns=['Cover_Type'])

In [33]:
y_score.head(5)

       Cover_Type
Id
15121           1
15122           1
15123           2
15124           2
15125           2

In [34]:
y_score.to_csv('submission.csv')
# V1: 0.74034
# V2: 0.73834